development:
  clients:
    default:
      database: damoa  # 데이터베이스 이름
      hosts:
        - localhost:27017  # MongoDB 호스트와 포트

spring:
  data:
    mongodb:
      # user: username
      # password: password
      uri: mongodb://localhost:27017/damoa

logging:
  level:
    org.mongodb: DEBUG  # MongoDB 로깅 콘솔 출력
    org.springframework.data.mongodb: DEBUG  # Spring Data MongoDB 로깅 콘솔 출력
